[package]
name = "roe"
version = "0.0.10" # remember to set `html_root_url` in `src/lib.rs`.
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT AND Unicode-3.0"
edition = "2024"
rust-version = "1.85.0"
readme = "README.md"
repository = "https://github.com/artichoke/roe"
documentation = "https://docs.rs/roe"
homepage = "https://github.com/artichoke/roe"
description = "Unicode case conversion"
keywords = ["capitalize", "case", "lowercase", "unicode", "uppercase"]
categories = ["encoding", "internationalization", "no-std", "no-std::no-alloc", "text-processing"]
include = ["/benches/**/*", "/src/**/*", "/generated/**/*", "/tests/**/*", "/LICENSE", "/LICENSE-UNICODE", "/README.md"]

[features]
default = ["alloc"]
# Enable a dependency on `alloc`, The Rust collections library. This feature
# enables APIs that depend on `Vec` and `String`.
alloc = []

[dependencies]
bstr = { version = "1.0.1", default-features = false }

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu` and only builds
# that target. `roe` has the same API and code on all targets.
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "case_mapping"
harness = false

[[bench]]
name = "case_mapping_changes"
harness = false
required-features = ["alloc"]

[[bench]]
name = "case_mapping_allocations"
harness = false
required-features = ["alloc"]
