#!/usr/bin/env ruby
# frozen_string_literal: true

# Generated sources incorporate Unicode Data Files and are distributed under
# both LICENSE (MIT) and LICENSE-UNICODE (Unicode License v3).

repo = File.expand_path('..', __dir__)
Dir.chdir(repo)
ucd = File.join(repo, 'generated', 'ucd')
version = File.read(File.join(ucd, 'ReadMe.txt'))[/final data files for version (\d+\.\d+\.\d+)/, 1]
abort 'Missing final Unicode version.' unless version

maps = { 'LOWER' => {}, 'UPPER' => {}, 'TITLE' => {}, 'FOLD' => {} }
File.foreach(File.join(ucd, 'UnicodeData.txt')) do |line|
  fields = line.chomp.split(';', -1)
  code = fields[0].to_i(16)
  { 'UPPER' => 12, 'LOWER' => 13, 'TITLE' => 14 }.each do |name, index|
    target = fields[index]
    target = fields[12] if name == 'TITLE' && target.empty?
    maps[name][code] = [target.to_i(16)] unless target.empty?
  end
end

%w[SpecialCasing CaseFolding].each do |name|
  path = File.join(ucd, "#{name}.txt")
  abort "#{name} version differs from #{version}." unless File.foreach(path).first.include?("#{name}-#{version}.txt")
end

File.foreach(File.join(ucd, 'SpecialCasing.txt')) do |line|
  data = line.split('#', 2).first.strip
  next if data.empty?

  code, lower, title, upper, condition = data.split(';').map(&:strip)
  # MRI's full mapping is context-independent; language-specific mappings are
  # selected at runtime. Lithuanian currently aliases full mapping in MRI.
  next unless condition.nil? || condition.empty?

  { 'LOWER' => lower, 'UPPER' => upper, 'TITLE' => title }.each do |name, target|
    maps[name][code.to_i(16)] = target.split.map { |value| value.to_i(16) }
  end
end

File.foreach(File.join(ucd, 'CaseFolding.txt')) do |line|
  data = line.split('#', 2).first.strip
  next if data.empty?

  code, status, target = data.split(';').map(&:strip)
  next unless %w[C F].include?(status)

  maps['FOLD'][code.to_i(16)] = target.split.map { |value| value.to_i(16) }
end

File.open('generated/case_mapping.rs', 'w') do |output|
  output.puts <<~HEADER
    // @generated by scripts/gen_case_lookups.rb. Do not edit.
    // Unicode #{version}. Derived from Unicode Data Files.
    // Copyright Unicode, Inc. See LICENSE-UNICODE and LICENSE.
  HEADER
  maps.each do |name, table|
    output.puts "\npub const #{name}: &[(u32, [u32; 3])] = &["
    table.sort.each do |code, target|
      next if target == [code]
      raise "Unsupported mapping: #{name} U+#{code.to_s(16)}" unless (1..3).cover?(target.length)
      raise 'Invalid scalar value.' unless ([code] + target).all? { |c| (0..0x10ffff).cover?(c) && !(0xd800..0xdfff).cover?(c) }

      values = target.map { |value| "0x#{value.to_s(16).upcase}" }
      values << '!0' until values.length == 3
      output.puts "    (0x#{code.to_s(16).upcase}, [#{values.join(', ')}]),"
    end
    output.puts '];'
  end
end
abort 'Rust formatting failed.' unless system('cargo', 'fmt', '--all')
