#!/usr/bin/env ruby
# frozen_string_literal: true

# Generated sources incorporate Unicode Data Files and are distributed under
# both LICENSE (MIT) and LICENSE-UNICODE (Unicode License v3).

class CaseMappingGenerator
  UNICODE_DATA_COLUMNS = { 'UPPER' => 12, 'LOWER' => 13, 'TITLE' => 14 }.freeze
  MAPPING_NAMES = %w[LOWER UPPER TITLE FOLD].freeze

  def initialize(repo:)
    @repo = repo
    @ucd = File.join(repo, 'generated', 'ucd')
  end

  def generate
    version = read_version
    validate_versions(version)
    mappings = load_mappings
    validate_mappings(mappings)
    write_rust(version, mappings)
    raise 'Rust formatting failed.' unless system('cargo', 'fmt', '--all', chdir: @repo)
  end

  private

  def read_version
    readme = File.read(ucd_path('ReadMe'))
    version = readme[/final data files for version (\d+\.\d+\.\d+)/, 1]
    raise 'Missing final Unicode version.' unless version

    version
  end

  def validate_versions(version)
    %w[SpecialCasing CaseFolding].each do |name|
      header = File.foreach(ucd_path(name)).first
      raise "#{name} version differs from #{version}." unless header.include?("#{name}-#{version}.txt")
    end
  end

  def load_mappings
    mappings = MAPPING_NAMES.to_h { |name| [name, {}] }
    load_unicode_data(mappings)
    load_special_casing(mappings)
    load_case_folding(mappings)
    mappings
  end

  def load_unicode_data(mappings)
    File.foreach(ucd_path('UnicodeData')) do |line|
      fields = line.chomp.split(';', -1)
      code = fields[0].to_i(16)
      UNICODE_DATA_COLUMNS.each do |name, index|
        target = fields[index]
        target = fields[12] if name == 'TITLE' && target.empty?
        mappings[name][code] = [target.to_i(16)] unless target.empty?
      end
    end
  end

  def load_special_casing(mappings)
    each_record('SpecialCasing') do |code, lower, title, upper, condition|
      # MRI's full mapping is context-independent; language-specific mappings
      # are selected at runtime. Lithuanian currently aliases full mapping.
      next unless condition.nil? || condition.empty?

      { 'LOWER' => lower, 'UPPER' => upper, 'TITLE' => title }.each do |name, target|
        mappings[name][code.to_i(16)] = parse_mapping(target)
      end
    end
  end

  def load_case_folding(mappings)
    each_record('CaseFolding') do |code, status, target|
      next unless %w[C F].include?(status)

      mappings['FOLD'][code.to_i(16)] = parse_mapping(target)
    end
  end

  def each_record(name)
    File.foreach(ucd_path(name)) do |line|
      data = line.split('#', 2).first.strip
      next if data.empty?

      yield(*data.split(';').map(&:strip))
    end
  end

  def parse_mapping(target)
    target.split.map { |value| value.to_i(16) }
  end

  def validate_mappings(mappings)
    mappings.each do |name, table|
      table.each do |code, target|
        raise "Unsupported mapping: #{name} U+#{code.to_s(16)}" unless (1..3).cover?(target.length)
        raise 'Invalid scalar value.' unless ([code] + target).all? { |value| scalar?(value) }
      end
    end
  end

  def scalar?(value)
    (0..0x10ffff).cover?(value) && !(0xd800..0xdfff).cover?(value)
  end

  def write_rust(version, mappings)
    File.open(File.join(@repo, 'generated', 'case_mapping.rs'), 'w') do |output|
      output.puts <<~HEADER
        // @generated by scripts/gen_case_lookups.rb. Do not edit.
        // Unicode #{version}. Derived from Unicode Data Files.
        // Copyright Unicode, Inc. See LICENSE-UNICODE and LICENSE.
      HEADER
      mappings.each { |name, table| write_table(output, name, table) }
    end
  end

  def write_table(output, name, table)
    output.puts "\npub const #{name}: &[(u32, [u32; 3])] = &["
    table.sort.each do |code, target|
      next if target == [code]

      values = target.map { |value| rust_hex(value) }
      values << '!0' until values.length == 3
      output.puts "    (#{rust_hex(code)}, [#{values.join(', ')}]),"
    end
    output.puts '];'
  end

  def rust_hex(value)
    "0x#{value.to_s(16).upcase}"
  end

  def ucd_path(name)
    File.join(@ucd, "#{name}.txt")
  end
end

CaseMappingGenerator.new(repo: File.expand_path('..', __dir__)).generate if $PROGRAM_NAME == __FILE__
